### ISSUE TITLE
Redundant requirement for jar to exist.

### ISSUE THREAD

**Issue by lewisakura** [TorchPowered/MapApplier#1]
Current code requires the jar to exist before the program is run, when it should just be created when required.

**Comment by PizzaCrust** [comment]
Will do.

**Comment by lewisakura** [comment]
Don't worry, I did it for you ;)

**Comment by PizzaCrust** [comment]
@LewisTehMinerz That file is not zip formatted!

**Comment by lewisakura** [comment]
@PizzaCrust Should be fixed now.

**Comment by lewisakura** [comment]
@PizzaCrust Just did a little bit of compiling in NetBeans, just pushed it now. Just noticed the diff is messed up, but it doesn't matter.

**Comment by PizzaCrust** [comment]
I forgot to tell you that the Java version will deprecated for the Kotlin one. Anyways, you have an email?

**Comment by lewisakura** [comment]
Yes, how else would I be on GitHub? Speaking of Kotlin, I don't think NetBeans is going to like that without an external plugin, but it's slow enough as it is...

**Comment by PizzaCrust** [comment]
Email? We should transfer this to Slack.

**Comment by lewisakura** [comment]
What's the Slack domain? Or has it not been created?

**Comment by PizzaCrust** [comment]
https://torchpowered.slack.com

**Comment by lewisakura** [comment]
Okay, let's get this done quick. Tell me when you want my E-Mail. I can't login due to me not having a password. (and registering is creating a new team)

**Comment by PizzaCrust** [comment]
Right now?

**Comment by lewisakura** [comment]
Yup

**Comment by lewisakura** [comment]
It'll be deleted basically instantly.

**Comment by lewisakura** [comment]
I'm ready when you are.

**Comment by PizzaCrust** [comment]
Ok, right now.

**Comment by LewisTehMinerz** [comment]
lewisminecraft@hotmail.co.uk

Tell me when you have it.

**Comment by PizzaCrust** [comment]
Done.

**Comment by lewisakura** [comment]
Okay

**Comment by PizzaCrust** [comment]
accept

**Comment by lewisakura** [comment]
Slack time

**Comment by lewisakura** [comment]
Heh, not entering my last name Slack! Also, zzzzzz

**Comment by PizzaCrust** [comment]
Alrighty.
